# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs <- function(data_length, dim, data_raw, data_raw_result, alpha, burn_in, iteration) {
    .Call('_CRPClustering_gibbs', PACKAGE = 'CRPClustering', data_length, dim, data_raw, data_raw_result, alpha, burn_in, iteration)
}

